### ISSUE TITLE
nightwatch-cucumber marked passed for failed cases

### ISSUE THREAD

**Issue by selident** [mucsi96/nightwatch-cucumber#49] opened 2016-04-06 09:14 UTC
I'm new with nightwatch-cucumber. I wrote 3 scenarios and they are failed. The console log also shows they failed. But in conclusion the result shows 3 scenarios passed!!!

Please take a look at screenshot. Was it an issue or I missed something?

![image 6](https://cloud.githubusercontent.com/assets/11884823/14311658/aef47e42-fc12-11e5-8806-03f374bdf5e8.png)

**Comment by mucsi96** [comment] 2016-04-06 09:47
Can we discuss it here https://gitter.im/mucsi96/nightwatch-cucumber ?

**Comment by selident** [comment] 2016-04-07 06:44
[features.zip](https://github.com/mucsi96/nightwatch-cucumber/files/207838/features.zip)

Hello @mucsi96 

I didn't see where to put attachment in gitter, so I put here.

Please kindly get attachment and reproduce.

Much appreciate your help.

**Comment by mucsi96** [comment] 2016-04-07 06:58
I think the problem is with how you are using `this.perform`. You should return immediately after calling`this.perform` because its asynchronous. So I propose to use `return this.perform(function () ...)` and move the code after the code inside the callback function. 

Is it working for you? Can I close the issue?

**Comment by selident** [comment] 2016-04-07 07:17
![image 8](https://cloud.githubusercontent.com/assets/11884823/14343476/6d1fdc6e-fccb-11e5-923b-1bc5233eb03e.png)
Issue still exists. Please take a look.

**Comment by mucsi96** [comment] 2016-04-07 11:10
Thanks for your feedback! I will check it

**Comment by mucsi96** [comment] 2016-04-08 07:43
A fix is released in version `2.1.6`. Thanks for help!

**Closed by mucsi96** 2016-04-08 07:43 UTC
Labels: bug
