### ISSUE TITLE
Unhandled Assertion Error

### ISSUE THREAD

**Issue by kerimovaa** [mucsi96/nightwatch-cucumber#255] opened 2017-08-07 12:11 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
I found unhandled Assertion Error after use chai expects. (`expect(result).to.equal('some text');`). Because of this error, processes are not interrupted and hang.
`AssertionError
         + expected - actual
         -Математика на м. Новые черемушки
         +some text
         at Object.<anonymous> (../../../../src/__e2e__/step_definitions/desktop/test_steps.js:16:18)
         at Object.<anonymous> (/Users/asifkerimov/Documents/autotests/warp/node_modules/nightwatch/lib/api/element-commands.js:361:20)
         at HttpRequest.<anonymous> (/Users/asifkerimov/Documents/autotests/warp/node_modules/nightwatch/lib/index.js:366:18)
         at emitTwo (events.js:125:13)
         at HttpRequest.emit (events.js:213:7)
         at HttpRequest.<anonymous> (/Users/asifkerimov/Documents/autotests/warp/node_modules/nightwatch/lib/index.js:382:15)
         at emitThree (events.js:135:13)
         at HttpRequest.emit (events.js:216:7)
         at IncomingMessage.<anonymous> (/Users/asifkerimov/Documents/autotests/warp/node_modules/nightwatch/lib/http/request.js:166:16)
         at emitNone (events.js:110:20)
         at IncomingMessage.emit (events.js:207:7)
         at endReadableNT (_stream_readable.js:1045:12)
         at _combinedTickCallback (internal/process/next_tick.js:102:11)
         at process._tickCallback (internal/process/next_tick.js:161:9)`

And that is all. Hanging. All processes can be interrupt only manually (that is big problem for our CI)
**Expected/desired behavior**
Errors must be handled and after another fatal errors node and selenium processes must be interrupt. 

**Reproduction of the problem**
You can reproduce this if you launch my test feature (files are linked in the end) .

**What is the expected behavior?**
After error all processes must be interrupted and ended.

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**
* **nightwatch-cucumber version:**
"7.1.9"
* **nightwatch version:**
"0.9.16"
* **cucumber version:**
"2.3.0"
* **Node.js version:**
"8.1.0"

*Attached files**
https://yadi.sk/d/3gU2KMBw3LnGCA
https://yadi.sk/d/z5LI8eqC3LnGFU

**Comment by mucsi96** [comment] 2017-08-12 18:02
This must be a duplicate of #244

**Closed by mucsi96** 2017-08-12 18:02 UTC

**Comment by kerimovaa** [comment] 2017-08-14 12:28
@mucsi96 I dont think so because in this case i required Chai directly. You can see in testSteps.js 
let expect = require('chai').expect;

**Comment by mucsi96** [comment] 2017-08-14 12:31
But chai is not compatible with nightwatch. Thats why an integration package is needed. Chai is throwing errors. Nightwatch assertions works totally diferently
