### ISSUE TITLE
strange behavior after update

### ISSUE THREAD

**Issue by Alfredo81** [mucsi96/nightwatch-cucumber#72] opened 2016-05-27 15:27 UTC
Using page-object tests after the last update of nightwatch  after launching nightwatch -e chrome,the test don't start and i've this output :

Warnings:

1) Scenario: First try google - features/google.feature:4
   Step: Given I open google home page - features/google.feature:6
   Message:
     Undefined. Implement with the following snippet:

       this.Given(/^I open google home page$/, function (callback) {
         // Write code here that turns the phrase above into concrete actions
         callback(null, 'pending');
       });

is it possible that is a regression for the update?

thank you,
Alfredo

**Comment by mucsi96** [comment] 2016-05-27 19:19
Thank you for the feedback! Can you provide a simple test case to reproduce the issue? It would be very helpfull.

Thanks
Igor

**Comment by mucsi96** [comment] 2016-05-27 19:59
Because the page-obeject test associated with the build passed successfully

**Comment by Alfredo81** [comment] 2016-05-30 08:52
try with this:
step.js:
module.exports = function() {
  this.Given(/^I open home page$/, function () {
     this.page.homepageFooter.footerAboutClick()
      
  })

  this.Then(/^Then I click About on footer$/, function () {
   this.page.homepageFooter.footerPress()
      
  })
};

and in page-object use homepageFooter.js that contains:

module.exports = function () {
  this.footerAboutClick = function() {
      browser
          .url("http://someurl")
          .waitForElementVisible('body', 10000)
          .windowMaximize()
          .refresh()
          .click(".someclass")
          .pause(1000)
 }
 
  this.footerPress = function() {
    browser
    .click(".someclass")
    return browser
  }
}

**Comment by mucsi96** [comment] 2016-05-30 11:30
@Alfredo81 your page-object definitions are wrong. Please read http://nightwatchjs.org/guide#page-objects
A working example would be
```
#features/test.feature
Feature: Test feature
Scenario: Test scenario

  Given I open home page
  Then Then I click About on footer
```

```
//features/step_definitions/step.js
module.exports = function() {
  this.Given(/^I open home page$/, function() {
    var homepageFooter = this.page.homepageFooter();
    homepageFooter.footerAboutClick()

  })

  this.Then(/^Then I click About on footer$/, function() {
    var homepageFooter = this.page.homepageFooter();
    homepageFooter.footerPress()

  })
};

```


```
//page-objects/homepageFooter.js
var footerCommands = {
    footerAboutClick: function() {
      return this.api
        .url("http://google.com")
        .waitForElementVisible('body', 10000)
        .windowMaximize()
        .refresh()
        .click("input[type='submit']")
        .pause(1000);
    },
    footerPress: function() {
      return this
        .click("input[type='submit']")
    }
  }

module.exports = {
  commands: [footerCommands],
  elements: {}
}
```

**Comment by Alfredo81** [comment] 2016-05-31 13:37
@mucsi96  first of all thank you so much for your help Igor.Unfortunately  for this example the output is 
"Running:  Test Scenario
  Scenario: Test Scenario

[TypeError: homepageFooter.footerAboutClick is not a function]
[TypeError: homepageFooter.footerPress is not a function] "

**Comment by mucsi96** [comment] 2016-05-31 16:31
@Alfredo81 It was working on my machine. Please provide the result of the following command executed from the project root `npm ls --depth 0`

**Comment by Alfredo81** [comment] 2016-06-01 07:48
Igor this is the output of npm ls --depth 0 from the project root

iMac-3:NewRelease pippo$ npm ls --depth 0
nightwatch-cucumber@2.3.3 /Users/morettaa/Desktop/NewRelease
├── chromedriver@2.21.2
├── co@4.6.0
├── glob@7.0.3
├── lodash@4.13.1
├── mkdirp@0.5.1
├── object-assign@4.1.0
├── phantomjs-prebuilt@2.1.7
├── resolve@1.1.7
├── selenium-server@2.53.0
├── semver@5.1.0
├── syntax-error@1.1.6
└── tmp@0.0.28

**Comment by Alfredo81** [comment] 2016-06-01 10:00
after the update at nightwatch-cucumber 3.0.0 the problem persist but the error is only this:
[TypeError: homepageFooter.footerAboutClick is not a function]
[TypeError: homepageFooter.footerPress is not a function]
No assertions ran.

1 scenario (1 passed)
0 steps
0m00.000s

and the npm ls --depth 0 output is :
nightwatch-cucumber@3.0.0 /Users/pippo/Desktop/NewRelease
├── chromedriver@2.21.2
├── co@4.6.0
├── cucumber@0.10.4
├── glob@7.0.3
├── lodash@4.13.1
├── mkdirp@0.5.1
├── nightwatch@0.9.1
├── object-assign@4.1.0
├── phantomjs-prebuilt@2.1.7
├── pre-commit@1.1.3
├── resolve@1.1.7
├── selenium-server@2.53.0
├── semver@5.1.0
├── snazzy@4.0.0
├── standard@7.1.1
├── syntax-error@1.1.6
└── tmp@0.0.28

**Comment by mucsi96** [comment] 2016-06-01 10:06
According to the output you cloned the nightwatch-cucumber project to NewRelease folder
This is not how it should be used. Please read the installation section of the readme: https://github.com/mucsi96/nightwatch-cucumber#installation

**Comment by Alfredo81** [comment] 2016-06-01 10:53
sorry igor my fault (i've tried some experiment with the hope that's  work cloning the nightwatch cucumber to new release as you correctly said).My first npm ls --depth 0 (i've followed your readme at the start) is :
/Users/pippo/NewRelease
├── chromedriver@2.21.2
├── cucumber@1.0.0
├── nightwatch@0.9.1
├── nightwatch-cucumber@3.0.0
├── phantomjs-prebuilt@2.1.7
└── selenium-server@2.53.0

and the error persist with this output:
TypeError: homepageFooter.footerAboutClick is not a function
    at Object.<anonymous> (/Users/pippo/NewRelease/features/step_definitions/steps.js:4:24)
    at Object.run (/usr/local/lib/node_modules/cucumber/lib/cucumber/util/run.js:30:19)
    at Object.invoke (/usr/local/lib/node_modules/cucumber/lib/cucumber/support_code/step_definition.js:100:21)
    at Object.execute (/Users/pippo/NewRelease/node_modules/nightwatch-cucumber/lib/nightwatch-runner.js:230:29)
    at /Users/pippo/NewRelease/node_modules/nightwatch-cucumber/lib/nightwatch-runner.js:301:12
    at Array.forEach (native)
    at Object.feature.discovered.(anonymous function) [as First try prova] (/Users/pippo/NewRelease/node_modules/nightwatch-cucumber/lib/nightwatch-runner.js:298:11)
    at Module.call (/usr/local/lib/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /usr/local/lib/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)
TypeError: homepageFooter.footerPress is not a function
    at Object.<anonymous> (/Users/pippo/NewRelease/features/step_definitions/steps.js:12:24)
    at Object.run (/usr/local/lib/node_modules/cucumber/lib/cucumber/util/run.js:30:19)
    at Object.invoke (/usr/local/lib/node_modules/cucumber/lib/cucumber/support_code/step_definition.js:100:21)
    at Object.execute (/Users/pippo/NewRelease/node_modules/nightwatch-cucumber/lib/nightwatch-runner.js:230:29)
    at /Users/pippo/NewRelease/node_modules/nightwatch-cucumber/lib/nightwatch-runner.js:301:12
    at Array.forEach (native)
    at Object.feature.discovered.(anonymous function) [as First try prova] (/Users/pippo/NewRelease/node_modules/nightwatch-cucumber/lib/nightwatch-runner.js:298:11)
    at Module.call (/usr/local/lib/node_modules/nightwatch/lib/runner/module.js:62:34)
    at /usr/local/lib/node_modules/nightwatch/lib/runner/testcase.js:70:29
    at _fulfilled (/usr/local/lib/node_modules/nightwatch/node_modules/q/q.js:834:54)

Thanks for helping mate

**Comment by mucsi96** [comment] 2016-06-01 11:22
Please checkout a newly created working test project: https://github.com/mucsi96/nw-cu-test

**Comment by Alfredo81** [comment] 2016-06-01 16:07
ok i found the error and was my fault(the new project is very useful for find the error).Thanks a lot for your support igor!i appreciate it!

**Comment by mucsi96** [comment] 2016-06-01 16:45
cool! no problem :) I am closing this issue.

**Closed by mucsi96** 2016-06-01 16:45 UTC
