### ISSUE TITLE
Nighwatch does not exit properly. Chromedriver still in execution. Possible solution provided

### ISSUE THREAD

**Issue by kabomi** [mucsi96/nightwatch-cucumber#270] opened 2017-08-23 09:17 UTC
**I'm submitting a ...**  (check one with "x")
```
[X] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
Nighwatch does not exit properly. Browser and chromedriver still in execution, even thought an error ocurred.
After `Ctrl+c` chromedriver process is still in execution

**Expected/desired behavior**
Nightwatch-cucumber executes the right nightwatch termination code.
That way, the nightwatch & chromedriver process will terminate.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://c9.io, http://www.koding.com, https://www.nitrous.io or similar.
```bash
git clone https://github.com/kabomi/nw-cucumber-not-exiting.git
cd nw-cucumber-not-exiting
npm install
nightwatch -c nightwatch-conf.js
```
**Hint to a solution**
[An example of what's probably needed to be done](https://github.com/kabomi/nw-cucumber-not-exiting#possible-solution)

**What is the expected behavior?**
Nightwatch-cucumber executes the right nightwatch termination code.
That way, the nightwatch & chromedriver process will terminate.

**What is the motivation / use case for changing the behavior?**
Jenkins builds timeout because of nightwatch process not exiting.

**Please tell us about your environment:**
MacOs Sierra 10.12.5

* output of the following command from your project root `npm ls nightwatch cucumber nightwatch-cucumber && node --version`
```bash
├── cucumber@2.3.1
├── nightwatch@0.9.16
└── nightwatch-cucumber@7.1.10

v6.9.1
```

**Comment by kabomi** [comment] 2017-08-23 09:56
With the latest version `7.3.1`
I noticed that the process terminate more often. But the chromedriver remains still in execution.
```
├── cucumber@2.3.1
├── nightwatch@0.9.16
└── nightwatch-cucumber@7.3.1

v6.9.1
```

```bash
~/p/s/nw-cucumber-not-exiting (master) $ ps xa | grep chrome
26040 s023  S+     0:00.00 grep --color=auto chrome
25944 s024  S+     0:00.06 node /Users/.../node_modules/chromedriver/bin/chromedriver --port=27114
25945 s024  S+     0:00.08 /Users/.../node_modules/chromedriver/lib/chromedriver/chromedriver --port=27114
```

**Comment by mucsi96** [comment] 2017-08-25 12:16
Hi @kabomi! Thanks for perfectly submitted issue with a lot a details. Checking ...

**Comment by mucsi96** [comment] 2017-08-25 17:26
Hi @kabomi! I made a timeout handling fix in version `8.0.2`. Can you try that? 
Actually the problem was much more complicated. My solution was to entirely disable timeouts in Cucumber. They should be handled by Nightwatch. The problem that if Cucumber timeouts I am not able to stop Nightwatch as the timeouts here are handled on very low level (request).

**Comment by mucsi96** [comment] 2017-08-25 19:15
Sorry version `8.0.4`

**Comment by kabomi** [comment] 2017-08-30 13:56
Hi @mucsi96, thanks for taking a look into it. It is great that you find out those problems too 👍 
I wanted to give you an update as [I tried with version `8.0.5`](https://github.com/kabomi/nw-cucumber-not-exiting/tree/cucumber3) and the same issue is happening.
To make it shorter:
I think that the problem is in `nightwatch-api.js` that sometimes when there is a call to `_closeSession`, `this.client.terminate` function [is pointing to your code](https://github.com/mucsi96/nightwatch-cucumber/blob/master/lib/nightwatch-api.js#L256) instead of the original nightwatch code.

**Comment by kabomi** [comment] 2017-08-30 13:57
Hi @mucsi96, thanks for taking a look into it. It is great that you find out those problems too 👍 
I wanted to give you an update as [I tried with version `8.0.5`](https://github.com/kabomi/nw-cucumber-not-exiting/tree/cucumber3) and the same issue is happening.

To make it shorter:
I think that the problem is in `nightwatch-api.js` that sometimes when there is a call to `_closeSession`, `this.client.terminate` function [is pointing to your code](https://github.com/mucsi96/nightwatch-cucumber/blob/master/lib/nightwatch-api.js#L256) instead of the original nightwatch code.

**Comment by mucsi96** [comment] 2017-08-30 14:41
Now as you can see from the logs the issue is different. No timeout anymore. The problem is in your custom command. You are throwing Error in asynchronous [code](https://github.com/kabomi/nw-cucumber-not-exiting/blob/cucumber3/tests/page-objects/yahoo.js#L6). And that is not possible to catch. You should call the callback with error as [first argument instead](http://fredkschott.com/post/2014/03/understanding-error-first-callbacks-in-node-js/). Actually Nightwatch inself is not really [consistent](http://nightwatchjs.org/guide#1-function-style-commands).

**Comment by kabomi** [comment] 2017-08-31 15:04
@mucsi96 I completely forgot about that, thanks for the knowledge sharing!! Awesome 👍

**Comment by mucsi96** [comment] 2017-08-31 15:22
But actually you are still right. Even if something goes wrong it should not hang like this. So I am reopening the issue and will try to fix

**Comment by kabomi** [comment] 2017-09-01 15:32
Excellent, I collected more or less the flow of whats going on, hopefully it helps you finding a solution:

User thrown exception:
  ☐ Caught by bootstrap_node
  ☐ Caught by nightwatch/lib/runner/run

    - console log thrown error

  ☐ Caught by cucumber/lib/user_code_runner

    - creates new Error with propper description/stack trace
    - rejects the promise
  ☐ ... errors are properly handled up to nightwatch-cucumber
  ☐ Nighwatch-cucumber/lib/nightwatch-api finish running the tests & sets executionSuccess to false

    - ln:304 executionSuccess = yield * testRunner(modules)
    - tries to closeSession, that means running the original nightwatch client terminate code
      * it should have been, ln:~231 nightwatch/lib/index.js 
      * Nightwatch.prototype.terminate = function(deferred) {
    - but what happens is that nightwatch-cucumber code is executed instead
      * ln:257 this.client.get().terminate = () => {
      * https://github.com/mucsi96/nightwatch-cucumber/blob/master/lib/nightwatch-api.js#L257

**Comment by mucsi96** [comment] 2017-09-02 12:59
Fixed in https://github.com/mucsi96/nightwatch-cucumber/releases/tag/v8.0.6 .Thanks for your feedback! Thanks to You I improved and simplified the error handling a lot! 🎉

**Closed by mucsi96** 2017-09-02 12:59 UTC
Labels: bug

**Comment by kabomi** [comment] 2017-09-05 08:42
@mucsi96 great!! Thanks you for solving it! It works!

**Comment by nbirus** [comment] 2017-10-18 19:15
@mucsi96 Very helpful thank you!

**Comment by viveksgit** [comment] 2018-08-09 11:26
@mucsi96 the above issue occurs with v 9.1.2
