### ISSUE TITLE
screenshot is not taken in cucumber.html when test is run through selenium grid (hub/nodes) 

### ISSUE THREAD

**Issue by paleyss** [mucsi96/nightwatch-cucumber#142] opened 2016-11-11 01:12 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**
screenshot is not taken for the failed step in cucumber.html when the test is run through selenium grid (hub/nodes)

**Expected/desired behavior**
screenshot is taken for the failed step in cucumber.html

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://c9.io, http://www.koding.com, https://www.nitrous.io or similar.

**What is the expected behavior?**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **nightwatch-cucumber version:**

* **nightwatch version:**

* **cucumber version:**

* **Node.js version:**

**Comment by mucsi96** [comment] 2016-11-12 05:13
Hi @paleyss! Thanks for the feedback! Are you sure it is a problem with nightwatch-cucumber? Can you send send a PR. I have no experience with Selenium grids.

**Comment by paleyss** [comment] 2016-11-14 21:34
Hi Igor,

When I test using local selenium server and local web driver, the
screenshot is taken in report.html correctly. However, after changing the
'launch_url' option in nightwatch.conf.js file to selenium grid, I didn't
see the screenshot in report.html. However, I can see the screenshot is
taken successfully in 'screenshot' folder which configured in 'screenshots'
option in nightwatch.conf.js file.

To selenium grid, you can config 1 or 2 nodes (PC) locally for testing
purpose. As my node is for work, I can't share it to you for validation.

What is PR?

Thanks,
Paleyss

**Comment by mucsi96** [comment] 2016-11-16 06:13
Hi @paleyss! Thanks for clarification. I would like to ask you for help. Can you investigate this issue and find the root cause of the problem? I am rather busy right now. A pull request (PR) would be very appreciated :)

**Comment by paleyss** [comment] 2016-11-16 16:58
I will check this weekend. Currently working on other dev framework now
during working hrs.

**Comment by mucsi96** [comment] 2017-03-15 18:12
Hi @paleyss! Do you have any new on this topic?

**Comment by paleyss** [comment] 2017-03-23 20:06
I have the work change and the source code is not stored, so i can't work on this ticket.

**Comment by mucsi96** [comment] 2017-03-23 20:16
Ok thanks. Closing for now

**Closed by mucsi96** 2017-03-23 20:16 UTC
Labels: help wanted
