### ISSUE TITLE
No tests defined error when using Feature/Scenario tags

### ISSUE THREAD

**Issue by arozwalak** [mucsi96/nightwatch-cucumber#176] opened 2017-01-04 16:19 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report
[ ] feature request
[ ] support request => Please do not submit support request here, instead use https://groups.google.com/d/forum/nightwatch-cucumber
```

**Current behavior**

```
Error: No tests defined! using source folder: /var/folders/56/dfrz3zdd08sf6h4ws9cpvy940000gn/T/tmp-21204E2hDn5Udk4hq/test/features ; using tags: home
```

***Test example***
```
@home
Feature: As an Intermediary on "home" page

  Background:
    Given I am borrowers microsite

  Scenario: See 5 of 13 products on page load
    Then I can see 5 of 13 products
```

**Please tell us about your environment:**

* **nightwatch-cucumber version:**
5.6.6
* **nightwatch version:**
0.9.8
* **cucumber version:**
1.3.1
* **Node.js version:**
7.3.0

**Comment by mucsi96** [comment] 2017-01-04 16:23
Hi, thanks for feedback! Can you update cucumber, nightwatch and nightwatch-cucumber to latest and try to reproduce? I can fix issues only on the latest version

**Comment by JonWallsten** [comment] 2017-01-07 13:20
We are using feature tags in our project, and have been doing it since at least version 4 or 5. Maybe you have configured this wrong?

**Comment by matthewroach** [comment] 2017-01-07 21:50
I believe I am getting the same error, and have tracked down what's causing the issue. For me I am retro fitting cucumber onto an existing nightwatch test suite. If I try to run using the --tag option for a tag that's only in a feature I get the error when I have the `src_folders` set in my conf.js file. If I comment out the `src_folders` config the error goes away. If I run with a tag that's in both a feature file and a nightwatch test file no error.
It's only when it's just in a feature file.

**Comment by arozwalak** [comment] 2017-01-09 13:13
@mucsi96 thanks for response. I tried to upgrade to latest versions but this gets me another issue https://github.com/mucsi96/nightwatch-cucumber/issues/175

@matthewroach how do you add tags in test file? When I checked nightwatch docs for using without nightwatch-cucumber test file should export object ie:

```
module.exports = {
  '@tags': ['login', 'sanity'],
  'demo login test': function (client) {
     // test code
  }
};
```

while with nightwatch-cucumber I`m using this 

```
module.exports = function (client) {
     // test code
};
```

so I don't know how to add tags to test file

**Comment by arozwalak** [comment] 2017-01-09 13:28
it looks to me like nightwatch/cucumber can't find `@home` in feature files

**Comment by matthewroach** [comment] 2017-01-09 14:53
@arozwalak I didn't have any tags in my test files, only in my feature files

**Comment by mucsi96** [comment] 2017-01-11 20:57
Hi @arozwalak! Can you send a small example project where I can reproduce the issue? I have no idea what is the issue here.

**Comment by mucsi96** [comment] 2017-01-26 22:04
Please reopen the issue if you can reproduce it with the latest version. Please provide an example as well. Closing for now.

**Closed by mucsi96** 2017-01-26 22:04 UTC
